service: serverless-prisma

frameworkVersion: '>=1.9.0 <2.0.0'

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs6.10
  # deploymentBucket: ${env:AWS_S3_DEPLOYMENT_BUCKET}
  environment:
    PRISMA_DEBUG: ${env:PRISMA_DEBUG}
    PRISMA_ENDPOINT: ${env:PRISMA_ENDPOINT}
    PRISMA_SECRET: ${env:PRISMA_SECRET}
    PRISMA_SERVICE: ${env:PRISMA_SERVICE}

functions:
  graphql:
    name: serverless-prisma-graphql-${self:custom.stage}
    handler: src/graphql.handler
    events:
      - http:
          cors: true
          integration: lambda-proxy
          method: get
          path: /
      - http:
          cors: true
          integration: lambda-proxy
          method: post
          path: /
  playground:
    name: serverless-prisma-graphql-playground-${self:custom.stage}
    handler: src/playground.handler
    events:
      - http:
          cors: true
          integration: lambda-proxy
          method: get
          path: /playground
