service: 'serverless-prisma'

frameworkVersion: '>=1.9.0 <2.0.0'

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: yarn
    packagerOptions:
      flat: false  # Will set --flat on install (defaults to false)
      ignoreScripts: false  # Do not execute package.json hook scripts on install (defaults to false)

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  region: us-east-1
  runtime: nodejs6.10
  # deploymentBucket: ${env:AWS_S3_DEPLOYMENT_BUCKET}
  environment:
    PRISMA_DEBUG: ${env:PRISMA_DEBUG}
    PRISMA_ENDPOINT: ${env:PRISMA_ENDPOINT}
    PRISMA_SECRET: ${env:PRISMA_SECRET}

functions:
  graphql:
    name: serverless-prisma-graphql-${self:custom.stage}
    handler: src/graphql.handler
    events:
      - http:
          cors: true
          integration: lambda-proxy
          method: get
          path: /
      - http:
          cors: true
          integration: lambda-proxy
          method: post
          path: /
  playground:
    name: serverless-prisma-graphql-playground-${self:custom.stage}
    handler: src/playground.handler
    events:
      - http:
          cors: true
          integration: lambda-proxy
          method: get
          path: /playground
